version: "3.7"

services:
  database_crudnode: 
    image: postgres
    container_name: database_crudnode
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=crudnode
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: crudnode
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
   

volumes:
  pgdata:
    driver: local